MACOSX_SDK_VERSION:        # [osx]
  - '10.14'                # [osx and x86_64]
  - '13.3'                 # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.13'                # [osx]
channel_sources:
- freecad,conda-forge
channel_targets:
- freecad main