conda_forge_output_validation: true
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
os_version:
  linux_64: cos7
# We only have qt-main and qt-webengine builds for
# aarch64, not ppc64le
provider: {linux_aarch64: default}
github:
  branch_name: main
  tooling_branch_name: main
